name: Static analysis

on:
  push:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: '.'
          extensions: 'c,h,cpp,hpp,cc,hh,c++,h++,cxx,hxx,cu'
